=== Frankenstein-Labs/01.v/ee/app/validators/json_schemas/compliance_framework_template.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Schema for compliance framework template files",
  "type": "object",
  "required": [
    "version",
    "name",
    "description",
    "color",
    "requirements"
  ],
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "integer",
      "minimum": 1
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 255
    },
    "description": {
      "type": "string",
      "minLength": 1,
      "maxLength": 255
    },
    "color": {
      "type": "string",
      "pattern": "^#[0-9a-fA-F]{3,8}$",
      "maxLength": 10
    },
    "requirements": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/requirement"
      }
    }
  },
  "$defs": {
    "requirement": {
      "type": "object",
      "required": [
        "name",
        "description",
        "controls"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 512
        },
        "description": {
          "type": "string",
          "minLength": 1,
          "maxLength": 512
        },
        "controls": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/control"
          }
        }
      }
    },
    "control": {
      "type": "object",
      "required": [
        "name",
        "control_type",
        "expression"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "control_type": {
          "type": "string",
          "enum": [
            "internal",
            "external"
          ]
        },
        "expression": {
          "type": "object",
          "required": [
            "operator",
            "field",
            "value"
          ],
          "additionalProperties": false,
          "properties": {
            "operator": {
              "type": "string",
              "minLength": 1
            },
            "field": {
              "type": "string",
              "minLength": 1
            },
            "value": {}
          }
        }
      }
    }
  }
}

=== Frankenstein-Labs/01.v/ee/config/compliance_management/templates/nist_800-171_r3_cmmc.json
{
  "version": 1,
  "name": "NIST 800-171 Rev. 3 CMMC",
  "description": "NIST 800-171 Rev. 3 CMMC compliance requirements",
  "color": "#003E74",
  "requirements": [
    {
      "name": "03.01.04 Separation of Duties",
      "description": "a) Identify the duties of individuals requiring separation. b) Define system access authorizations to support separation of duties.",
      "controls": [
        {
          "name": "minimum_approvals_required_2",
          "control_type": "internal",
          "expression": {
            "field": "minimum_approvals_required",
            "operator": ">=",
            "value": 2
          }
        },
        {
          "name": "merge_request_prevent_author_approval",
          "control_type": "internal",
          "expression": {
            "field": "merge_request_prevent_author_approval",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "merge_request_prevent_committers_approval",
          "control_type": "internal",
          "expression": {
            "field": "merge_request_prevent_committers_approval",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "merge_requests_approval_rules_prevent_editing",
          "control_type": "internal",
          "expression": {
            "field": "merge_requests_approval_rules_prevent_editing",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "03.04.04 Impact Analyses",
      "description": "a) Analyze changes to the system to determine potential security impacts prior to change implementation. b) Verify that the security requirements for the system continue to be satisfied after the system changes have been implemented.",
      "controls": [
        {
          "name": "default_branch_protected",
          "control_type": "internal",
          "expression": {
            "field": "default_branch_protected",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "03.04.05 Access Restrictions for Change",
      "description": "a) Define, document, approve, and enforce physical and logical access restrictions associated with changes to the system.",
      "controls": [
        {
          "name": "default_branch_protected",
          "control_type": "internal",
          "expression": {
            "field": "default_branch_protected",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "03.04.10 System Component Inventory",
      "description": "a) Develop and document an inventory of system components. b) Review and update the system component inventory (organization-defined frequency). c) Update the system component inventory as part of installations, removals, and system updates.",
      "controls": [
        {
          "name": "scanner_license_compliance_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_license_compliance_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "03.05.07 Password Management",
      "description": "b) Verify that passwords are not found on the list of commonly used, expected, or compromised passwords when users create or update passwords. c) Transmit passwords only over cryptographically protected channels. d) Store passwords in a cryptographically protected form.",
      "controls": [
        {
          "name": "scanner_secret_detection_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_secret_detection_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "03.11.02 Vulnerability Monitoring and Scanning",
      "description": "a) Monitor and scan the system for vulnerabilities (organization-defined frequency) and when new vulnerabilities affecting the system are identified. c) Update system vulnerabilities to be scanned (organization-defined frequency) and when new vulnerabilities are identified and reported.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_sast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_sast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    }
  ]
}

=== Frankenstein-Labs/01.v/ee/config/compliance_management/templates/csa_ccm_v4.json
{
  "version": 1,
  "name": "CSA CCM v4",
  "description": "CSA CCM v4 compliance requirements",
  "color": "#2F5496",
  "requirements": [
    {
      "name": "CCC-02 Quality Testing",
      "description": "Follow a defined quality change control, approval and testing process with established baselines, testing, and release standards.",
      "controls": [
        {
          "name": "default_branch_protected",
          "control_type": "internal",
          "expression": {
            "field": "default_branch_protected",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_code_quality_running",
          "control_type": "internal",
          "expression": {
            "operator": "=",
            "field": "scanner_code_quality_running",
            "value": true
          }
        }
      ]
    },
    {
      "name": "CCC-04 Unauthorized Change Protection",
      "description": "Restrict the unauthorized addition, removal, update, and management of organization assets.",
      "controls": [
        {
          "name": "default_branch_protected",
          "control_type": "internal",
          "expression": {
            "field": "default_branch_protected",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "IAM-04 Separation of Duties",
      "description": "Employ the separation of duties principle when implementing information system access.",
      "controls": [
        {
          "name": "minimum_approvals_required_2",
          "control_type": "internal",
          "expression": {
            "field": "minimum_approvals_required",
            "operator": ">=",
            "value": 2
          }
        },
        {
          "name": "merge_request_prevent_author_approval",
          "control_type": "internal",
          "expression": {
            "field": "merge_request_prevent_author_approval",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "merge_request_prevent_committers_approval",
          "control_type": "internal",
          "expression": {
            "field": "merge_request_prevent_committers_approval",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "merge_requests_approval_rules_prevent_editing",
          "control_type": "internal",
          "expression": {
            "field": "merge_requests_approval_rules_prevent_editing",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "IAM-15 Passwords Management",
      "description": "Define, implement and evaluate processes, procedures and technical measures for the secure management of passwords.",
      "controls": [
        {
          "name": "scanner_secret_detection_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_secret_detection_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "TVM-05 External Library Vulnerabilities",
      "description": "Define, implement and evaluate processes, procedures and technical measures to identify updates for applications which use third party or open source libraries according to the organization's vulnerability management policy.",
      "controls": [
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "TVM-07 Vulnerability Identification",
      "description": "Define, implement and evaluate processes, procedures and technical measures for the detection of vulnerabilities on organizationally managed assets at least monthly.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_sast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_sast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    }
  ]
}

=== Frankenstein-Labs/01.v/ee/config/compliance_management/templates/cis_csc_v8-1.json
{
  "version": 1,
  "name": "CIS CSC v8.1",
  "description": "CIS CSC v8.1 compliance requirements",
  "color": "#003366",
  "requirements": [
    {
      "name": "6.7 Centralize Access Control",
      "description": "Centralize access control for all enterprise assets through a directory service or SSO provider, where supported.",
      "controls": [
        {
          "name": "auth_sso_enabled",
          "control_type": "internal",
          "expression": {
            "operator": "=",
            "field": "auth_sso_enabled",
            "value": true
          }
        }
      ]
    },
    {
      "name": "7.5 Perform Automated Vulnerability Scans of Internal Enterprise Assets",
      "description": "Perform automated vulnerability scans of internal enterprise assets on a quarterly, or more frequent, basis. Conduct both authenticated and unauthenticated scans.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "7.6 Perform Automated Vulnerability Scans of Externally-Exposed Enterprise Assets",
      "description": "Perform automated vulnerability scans of externally-exposed enterprise assets. Perform scans on a monthly, or more frequent, basis.",
      "controls": [
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "16.12 Implement Code-Level Security Checks",
      "description": "Apply static and dynamic analysis tools within the application lifecycle to verify that secure coding practices are being followed.",
      "controls": [
        {
          "name": "scanner_sast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_sast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_secret_detection_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_secret_detection_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    }
  ]
}

=== Frankenstein-Labs/01.v/ee/config/compliance_management/templates/ismap.json
{
  "version": 1,
  "name": "ISMAP",
  "description": "ISMAP compliance requirements",
  "color": "#D11919",
  "requirements": [
    {
      "name": "6.1.2 Segregation of duties",
      "description": "Conflicting duties and areas of responsibility should be segregated to reduce opportunities for unauthorized or unintentional modification or misuse of the organization's assets.",
      "controls": [
        {
          "name": "minimum_approvals_required_2",
          "control_type": "internal",
          "expression": {
            "field": "minimum_approvals_required",
            "operator": ">=",
            "value": 2
          }
        },
        {
          "name": "merge_request_prevent_author_approval",
          "control_type": "internal",
          "expression": {
            "field": "merge_request_prevent_author_approval",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "merge_request_prevent_committers_approval",
          "control_type": "internal",
          "expression": {
            "field": "merge_request_prevent_committers_approval",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "merge_requests_approval_rules_prevent_editing",
          "control_type": "internal",
          "expression": {
            "field": "merge_requests_approval_rules_prevent_editing",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "9.3.1 Use of secret authentication information",
      "description": "Users should be required to follow the organization's practices in the use of secret authentication information.",
      "controls": [
        {
          "name": "scanner_secret_detection_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_secret_detection_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "9.4.5 Access control to program source code",
      "description": "Access to program source code should be restricted.",
      "controls": [
        {
          "name": "default_branch_protected",
          "control_type": "internal",
          "expression": {
            "field": "default_branch_protected",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "12.1.2 Change management",
      "description": "Changes to the organization, business processes, information processing facilities and systems that affect information security should be controlled.",
      "controls": [
        {
          "name": "default_branch_protected",
          "control_type": "internal",
          "expression": {
            "field": "default_branch_protected",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "12.6.1 Management of technical vulnerabilities",
      "description": "Information about technical vulnerabilities of information systems being used should be obtained in a timely fashion, the organization's exposure to such vulnerabilities evaluated and appropriate measures taken to address the associated risk.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "14.2.1 Secure development policy",
      "description": "Rules for the development of software and systems should be established and applied to developments within the organization.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_sast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_sast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "14.2.1 Secure development policy 1",
      "description": "Rules for the development of software and systems should be established and applied to developments within the organization.",
      "controls": [
        {
          "name": "scanner_secret_detection_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_secret_detection_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "14.2.8 System security testing",
      "description": "Testing of security functionality should be carried out during development.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_sast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_sast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "14.2.8 System security testing 1",
      "description": "Testing of security functionality should be carried out during development.",
      "controls": [
        {
          "name": "scanner_secret_detection_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_secret_detection_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "18.1.2 Intellectual property rights",
      "description": "Appropriate procedures should be implemented to ensure compliance with legislative, regulatory and contractual requirements related to intellectual property rights and use of proprietary software products.",
      "controls": [
        {
          "name": "scanner_license_compliance_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_license_compliance_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    }
  ]
}
