=== Frankenstein-Labs/01.v/ee/app/validators/json_schemas/compliance_framework_template.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Schema for compliance framework template files",
  "type": "object",
  "required": [
    "version",
    "name",
    "description",
    "color",
    "requirements"
  ],
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "integer",
      "minimum": 1
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 255
    },
    "description": {
      "type": "string",
      "minLength": 1,
      "maxLength": 255
    },
    "color": {
      "type": "string",
      "pattern": "^#[0-9a-fA-F]{3,8}$",
      "maxLength": 10
    },
    "requirements": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/requirement"
      }
    }
  },
  "$defs": {
    "requirement": {
      "type": "object",
      "required": [
        "name",
        "description",
        "controls"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 512
        },
        "description": {
          "type": "string",
          "minLength": 1,
          "maxLength": 512
        },
        "controls": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/control"
          }
        }
      }
    },
    "control": {
      "type": "object",
      "required": [
        "name",
        "control_type",
        "expression"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "control_type": {
          "type": "string",
          "enum": [
            "internal",
            "external"
          ]
        },
        "expression": {
          "type": "object",
          "required": [
            "operator",
            "field",
            "value"
          ],
          "additionalProperties": false,
          "properties": {
            "operator": {
              "type": "string",
              "minLength": 1
            },
            "field": {
              "type": "string",
              "minLength": 1
            },
            "value": {}
          }
        }
      }
    }
  }
}

=== Frankenstein-Labs/01.v/ee/config/compliance_management/templates/nis_2.json
{
  "version": 1,
  "name": "NIS 2",
  "description": "NIS 2 compliance requirements",
  "color": "#004494",
  "requirements": [
    {
      "name": "Article 11 Requirements, technical capabilities and tasks of CSIRTs",
      "description": "3. The CSIRTs shall have the following tasks: a) monitoring and analysing cyber threats, vulnerabilities and incidents at national level and, upon request, providing assistance to essential and important entities concerned regarding real-time or near real-time monitoring of their network and information systems.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "Article 21 Cybersecurity risk-management measures",
      "description": "Implement cybersecurity measures based on all-hazards approach to protect systems from incidents, including supply chain security across direct suppliers and service providers, and security in network/information systems acquisition, development, maintenance, and vulnerability handling.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_sast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_sast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    }
  ]
}

=== Frankenstein-Labs/01.v/ee/config/compliance_management/templates/irap_protected.json
{
  "version": 1,
  "name": "IRAP Protected",
  "description": "IRAP Protected compliance requirements",
  "color": "#FFB800",
  "requirements": [
    {
      "name": "ISM-0402 Application security testing",
      "description": "Applications are comprehensively tested for vulnerabilities, using static application security testing and dynamic application security testing, prior to their initial release and any subsequent releases.",
      "controls": [
        {
          "name": "scanner_sast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_sast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "ISM-1163 Continuous monitoring plan",
      "description": "Systems have a continuous monitoring plan that includes: conducting vulnerability scans for systems at least fortnightly, conducting vulnerability assessments and penetration tests for systems prior to deployment, including prior to deployment of significant changes, and at least annually thereafter, analysing identified vulnerabilities to determine their potential impact, and implementing mitigations based on risk, effectiveness and cost.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "ISM-1422 Development, testing and production environments",
      "description": "Unauthorised access to the authoritative source for software is prevented.",
      "controls": [
        {
          "name": "default_branch_protected",
          "control_type": "internal",
          "expression": {
            "field": "default_branch_protected",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "ISM-1698 Scanning for unmitigated vulnerabilities",
      "description": "A vulnerability scanner is used at least daily to identify missing patches or updates for vulnerabilities in online services.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "ISM-1700 Scanning for unmitigated vulnerabilities",
      "description": "A vulnerability scanner is used at least fortnightly to identify missing patches or updates for vulnerabilities in applications other than office productivity suites, web browsers and their extensions, email clients, PDF software, and security products.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "ISM-1701 Scanning for unmitigated vulnerabilities",
      "description": "A vulnerability scanner is used at least daily to identify missing patches or updates for vulnerabilities in operating systems of internet-facing servers and internet-facing network devices.",
      "controls": [
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "ISM-1702 Scanning for unmitigated vulnerabilities",
      "description": "A vulnerability scanner is used at least fortnightly to identify missing patches or updates for vulnerabilities in operating systems of workstations, non-internet-facing servers and non-internet-facing network devices.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "ISM-1808 Scanning for unmitigated vulnerabilities",
      "description": "A vulnerability scanner with an up-to-date vulnerability database is used for vulnerability scanning activities.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "ISM-1816 Development, testing and production environments",
      "description": "Unauthorised modification of the authoritative source for software is prevented.",
      "controls": [
        {
          "name": "default_branch_protected",
          "control_type": "internal",
          "expression": {
            "field": "default_branch_protected",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "ISM-1875 Protecting credentials",
      "description": "Networks are scanned at least monthly to identify any credentials that are being stored in the clear.",
      "controls": [
        {
          "name": "scanner_secret_detection_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_secret_detection_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    }
  ]
}

=== Frankenstein-Labs/01.v/ee/config/compliance_management/templates/tisax.json
{
  "version": 1,
  "name": "TISAX",
  "description": "TISAX compliance requirements",
  "color": "#00205C",
  "requirements": [
    {
      "name": "1.2.2 To what extent are information security responsibilities organized?",
      "description": "A successful ISMS requires clear responsibilities within the organization. An appropriate organizational separation of responsibilities should be established in order to avoid conflict of interests (separation of duties). (C, I, A)",
      "controls": [
        {
          "name": "minimum_approvals_required_2",
          "control_type": "internal",
          "expression": {
            "field": "minimum_approvals_required",
            "operator": ">=",
            "value": 2
          }
        },
        {
          "name": "merge_request_prevent_author_approval",
          "control_type": "internal",
          "expression": {
            "field": "merge_request_prevent_author_approval",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "merge_request_prevent_committers_approval",
          "control_type": "internal",
          "expression": {
            "field": "merge_request_prevent_committers_approval",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "merge_requests_approval_rules_prevent_editing",
          "control_type": "internal",
          "expression": {
            "field": "merge_requests_approval_rules_prevent_editing",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "1.3.4 To what extent is it ensured that only evaluated and approved software is used for processing the organization's information assets?",
      "description": "Information processing is mostly done using of specific software. Security issues in software will easily become a risk for the information processed. Accordingly, software must be appropriately managed. Software is approved before installation or use. The software repositories are protected against unauthorized manipulation. Approval of software is regularly reviewed. Software versions and patch levels are known.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_license_compliance_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_license_compliance_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "5.2.1 To what extent are changes managed?",
      "description": "The objective is to ensure that information security aspects are considered in case of any changes to the organization, business processes and IT systems (Change Management) in order to prevent these changes from causing an uncontrolled reduction in the information security level. Information security requirements for changes to the organization, business processes, IT systems are determined and applied. A formal approval procedure is established.",
      "controls": [
        {
          "name": "default_branch_protected",
          "control_type": "internal",
          "expression": {
            "field": "default_branch_protected",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "5.2.5 To what extent are vulnerabilities identified and addressed?",
      "description": "Gather and evaluate information on technical vulnerabilities affecting IT systems. Identify and assess potentially affected systems and software, then address vulnerabilities based on risk assessment to prevent exploitation by attackers.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "5.3.1 To what extent is information security considered in new or further developed IT systems?",
      "description": "Incorporate information security throughout IT system lifecycle. Determine and address security requirements during design, development, acquisition, and system changes. Conduct security-focused approval testing for all IT systems.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_sast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_sast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "5.3.1 To what extent is information security considered in new or further developed IT systems? 1",
      "description": "Incorporate information security throughout IT system lifecycle. Determine and address security requirements during design, development, acquisition, and system changes. Conduct security-focused approval testing for all IT systems.",
      "controls": [
        {
          "name": "scanner_secret_detection_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_secret_detection_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "7.1.1 To what extent is compliance with regulatory and contractual provisions ensured?",
      "description": "Non-compliance with legal, regulatory, or contractual provisions can create risks to the information security of customers and the own organization. Therefore, it is essential to ensure that these provisions are known and observed. Legal, regulatory, and contractual provisions of relevance to information security (see examples) are determined at regular intervals.",
      "controls": [
        {
          "name": "scanner_license_compliance_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_license_compliance_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    }
  ]
}

=== Frankenstein-Labs/01.v/ee/config/compliance_management/templates/fedramp_low_r5.json
{
  "version": 1,
  "name": "FedRAMP Low",
  "description": "FedRAMP Low compliance requirements",
  "color": "#7B9CB7",
  "requirements": [
    {
      "name": "CM-5: Access Restrictions for Change",
      "description": "Define, document, approve, and enforce physical and logical access restrictions associated with changes to the system.",
      "controls": [
        {
          "name": "default_branch_protected",
          "control_type": "internal",
          "expression": {
            "field": "default_branch_protected",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "minimum_approvals_required_2",
          "control_type": "internal",
          "expression": {
            "field": "minimum_approvals_required",
            "operator": ">=",
            "value": 2
          }
        }
      ]
    },
    {
      "name": "CM-6: Configuration Settings",
      "description": "Establish and document secure configuration settings for system components; implement these settings; identify, document, and approve deviations based on operational requirements; and monitor and control changes to configurations according to organizational policies.",
      "controls": [
        {
          "name": "merge_request_prevent_author_approval",
          "control_type": "internal",
          "expression": {
            "field": "merge_request_prevent_author_approval",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "CM-7: Least Functionality",
      "description": "Configure the system to provide only organization-defined mission essential capabilities; and Prohibit or restrict the use of the following functions, ports, protocols, software, and/or services: organization-defined prohibited or restricted functions, system ports, protocols, software, and/or services.",
      "controls": [
        {
          "name": "merge_request_prevent_committers_approval",
          "control_type": "internal",
          "expression": {
            "field": "merge_request_prevent_committers_approval",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "merge_requests_approval_rules_prevent_editing",
          "control_type": "internal",
          "expression": {
            "field": "merge_requests_approval_rules_prevent_editing",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "CM-10: Software Usage Restrictions",
      "description": "Use software and associated documentation in accordance with contract agreements and copyright laws; track the use of software and associated documentation protected by quantity licenses to control copying and distribution; and control and document the use of peer-to-peer file sharing technology to ensure that this capability is not used for the unauthorized distribution, display, performance, or reproduction of copyrighted work.",
      "controls": [
        {
          "name": "scanner_license_compliance_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_license_compliance_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "IA-2(12): Acceptance of PIV Credentials",
      "description": "Accept and electronically verify Personal Identity Verification (PIV) credentials.",
      "controls": [
        {
          "name": "auth_sso_enabled",
          "control_type": "internal",
          "expression": {
            "operator": "=",
            "field": "auth_sso_enabled",
            "value": true
          }
        }
      ]
    },
    {
      "name": "IA-8(1): Acceptance of PIV Credentials From Other Agencies",
      "description": "Accept and electronically verify Personal Identity Verification (PIV) credentials from other federal agencies.",
      "controls": [
        {
          "name": "auth_sso_enabled",
          "control_type": "internal",
          "expression": {
            "operator": "=",
            "field": "auth_sso_enabled",
            "value": true
          }
        }
      ]
    },
    {
      "name": "RA-5: Vulnerability Monitoring and Scanning",
      "description": "Scan for vulnerabilities in the system and hosted applications; employ vulnerability scanning tools and techniques; analyze vulnerability scan reports and results; remediate legitimate vulnerabilities; and share vulnerability information.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_dast_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dast_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_api_security_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_api_security_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    }
  ]
}

=== Frankenstein-Labs/01.v/ee/config/compliance_management/templates/cyber_essentials.json
{
  "version": 1,
  "name": "Cyber Essentials",
  "description": "Cyber Essentials compliance requirements",
  "color": "#0072C6",
  "requirements": [
    {
      "name": "A6.2 Supported software",
      "description": "Is all the software on your devices supported by a supplier that produces regular fixes for any security problems? All software used by your organization must be supported by a supplier who provides regular security updates. Unsupported software must be removed from your devices. This includes frameworks and plugins such as Java, Adobe Reader and .NET.",
      "controls": [
        {
          "name": "scanner_dep_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_dep_scanning_running",
            "operator": "=",
            "value": true
          }
        },
        {
          "name": "scanner_container_scanning_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_container_scanning_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    },
    {
      "name": "A6.3 Software licensing",
      "description": "Is all software licensed in accordance with the publisher's recommendations? All software must be licensed. It is acceptable to use free and open source software as long as you comply with any licensing requirements.",
      "controls": [
        {
          "name": "scanner_license_compliance_running",
          "control_type": "internal",
          "expression": {
            "field": "scanner_license_compliance_running",
            "operator": "=",
            "value": true
          }
        }
      ]
    }
  ]
}
